### ISSUE TITLE
Independent routines

### ISSUE THREAD

**Issue by noisegul** [antoniogamiz/mini-doc#12]
Would it be possible to include routines that are not attached to a class or role?
In `master`, independent routines now reside in their own pod file.
They provide an edge case I'm missing from this repo right now for testing (especially `exit`).

**Comment by antoniogamiz** [comment]
Right now :D.

**Comment by antoniogamiz** [comment]
Is that enough?

**Comment by noisegul** [comment]
I believe that will suffice, thank you :)
